###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
  memcached:
    image: 'memcached:alpine'
    container_name: pipsi-memcached

  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: pipsi-mailhog
    ports:
      - '8025:8025'

  redis:
    image: 'redis:alpine'
    container_name: pipsi-redis

  mysql:
    image: 'mysql:5.7'
    container_name: pipsi-mysql
    working_dir: /application
    volumes:
      - '../code/www/PIPSIntervention:/application'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=default
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=myuser
    ports:
      - '3306:3306'

  clickhouse:
    image: 'yandex/clickhouse-server:latest'
    container_name: pipsi-clickhouse

  webserver:
    image: 'nginx:alpine'
    container_name: pipsi-webserver
    working_dir: /application
    volumes:
      - '../code/www/PIPSIntervention:/application'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

  php-fpm:
    build: phpdocker/php-fpm
    container_name: pipsi-php-fpm
    working_dir: /application
    volumes:
      - '../code/www/PIPSIntervention:/application'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
